### ISSUE TITLE
Make the checkpoint of the model available

### ISSUE THREAD

**Issue by elxavicio** [parachutel/deeplabv3plus_on_Mapillary_Vistas#1]
Hi, great work, it's been super useful! I believe it would be useful to share the model checkpoint, the same way as it's shared the cityscapes one. Would it be possible? Thanks a lot!

**Comment by parachutel** [comment]
Sorry for the late reply.

https://www.dropbox.com/sh/1gaat3kjgoe8rzz/AAAYcfsNlnd0uwHDtoG7r8HRa?dl=0

To use the checkpoint you will need to modify the path in the checkpoint file
``
model_checkpoint_path: "/home/user_name/models/research/deeplab/datasets/mvd/exp/exp_name/train/model.ckpt-xxxxx"
``

I hope this would help.

**Comment by wangergou135** [comment]
Hi, This link https://www.dropbox.com/sh/1gaat3kjgoe8rzz/AAAYcfsNlnd0uwHDtoG7r8HRa?dl=0
was no longer a valid link. Would you update the checkpoint again please, Thanks!

**Comment by parachutel** [comment]
It has been restored.
https://www.dropbox.com/sh/1gaat3kjgoe8rzz/AAAYcfsNlnd0uwHDtoG7r8HRa?dl=0

**Comment by elxavicio** [comment]
Thanks!

**Comment by yesusbc** [comment]
Hi!! Amazing work.
I'm having troubles exporting the checkpoint files as a frozen inference graph, if you have that file, could you upload it too?

**Comment by 16hchung** [comment]
@parachutel Thank you for making this available! Since the name of the dropbox dir you linked is "train_on_train_full_cityscapes...", I just wanted to confirm whether this is the checkpoint from training on mapillary?
